In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
filepath1 = os.path.join("Resources" ,"JC-201704-citibike-tripdata.csv")
filepath2 = os.path.join("Resources" ,"JC-201705-citibike-tripdata.csv")
filepath3 = os.path.join("Resources" ,"JC-201706-citibike-tripdata.csv")
filepath4 = os.path.join("Resources" ,"JC-201707-citibike-tripdata.csv")
filepath5 = os.path.join("Resources" ,"JC-201708 citibike-tripdata.csv")
filepath6 = os.path.join("Resources" ,"JC-201709-citibike-tripdata.csv")

jc_201704 = pd.read_csv(filepath1)
jc_201705 = pd.read_csv(filepath2)
jc_201706 = pd.read_csv(filepath3)
jc_201707 = pd.read_csv(filepath4)
jc_201708 = pd.read_csv(filepath5)
jc_201709 = pd.read_csv(filepath6)

In [3]:
jc_201706.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,499,2017-06-01 00:01:39,2017-06-01 00:09:59,3195,Sip Ave,40.730743,-74.063784,3194,McGinley Square,40.725340,-74.067622,29590,Subscriber,1979.0,1
1,507,2017-06-01 00:06:39,2017-06-01 00:15:07,3211,Newark Ave,40.721525,-74.046305,3277,Communipaw & Berry Lane,40.714358,-74.066611,29453,Subscriber,1969.0,1
2,768,2017-06-01 00:44:43,2017-06-01 00:57:31,3195,Sip Ave,40.730743,-74.063784,3189,West Side Light Rail,40.714402,-74.088772,26193,Subscriber,1962.0,1
3,101,2017-06-01 01:12:55,2017-06-01 01:14:36,3185,City Hall,40.717733,-74.043845,3213,Van Vorst Park,40.718489,-74.047727,29284,Subscriber,1983.0,1
4,265,2017-06-01 01:14:00,2017-06-01 01:18:25,3273,Manila & 1st,40.721651,-74.042884,3278,Monmouth and 6th,40.725685,-74.048790,29645,Subscriber,1980.0,2

In [4]:
jc_combined = pd.concat([jc_201704, jc_201705, jc_201706, jc_201707, jc_201708, jc_201709])
jc_combined.count()

tripduration               181376
starttime                  181376
stoptime                   181376
start station id           181376
start station name         181376
start station latitude     181376
start station longitude    181376
end station id             181376
end station name           181376
end station latitude       181376
end station longitude      181376
bikeid                     181376
usertype                   181376
birth year                 166921
gender                     181376
dtype: int64

In [5]:
jc_combined.to_csv("JC Combined Bike.csv", index=False)